### ISSUE TITLE
SharpDocx/SharpDocx/CodeBlocks/TextBlock.cs  Line71-75 has a bug

### ISSUE THREAD

**Issue by cnraorong** [egonl/SharpDocx#26] opened 2020-10-19 04:38 UTC
SharpDocx/SharpDocx/CodeBlocks/TextBlock.cs,   when nextElement.NextSibling() is null, the program will crash.....

**Comment by cnraorong** [comment] 2020-10-19 04:41
add some codes like next,   successful   ...  :)
if (nextElement == null)  { break;  }

**Comment by egonl** [comment] 2020-10-19 18:56
I tried to reproduce this, but without success. Do you have an example view for me?

**Comment by egonl** [comment] 2020-11-11 17:00
Can't reproduce, reporter afk. Closing issue.

**Closed by egonl** 2020-11-11 17:00 UTC
