### ISSUE TITLE
System.ArgumentException: 'baseClass should be a DocumentBase derived type Parameter name: baseClass'

### ISSUE THREAD

**Issue by aman-gill-97** [egonl/SharpDocx#67] opened 2024-04-11 06:48 UTC
![Capture](https://github.com/egonl/SharpDocx/assets/147373626/87c26392-5ef7-4720-93b3-d67cb6d30e27)

**Comment by egonl** [comment] 2024-04-11 07:14
Please provide a solution where this issue can be reproduced. Either a repo or a zip.

**Comment by aman-gill-97** [comment] 2024-04-11 07:50
We are trying to build a word addin using sharpdocx at the backend

**Comment by aman-gill-97** [comment] 2024-04-11 07:51
I am sharing the solution in a zip file below let me know if you need something else

**Comment by aman-gill-97** [comment] 2024-04-11 08:11
[Sharpdocx.Wordaddin.zip](https://github.com/egonl/SharpDocx/files/14943233/Sharpdocx.Wordaddin.zip)
Here i am attaching the solution file, you can use this to reproduce the error

**Comment by egonl** [comment] 2024-04-11 17:37
Thanks for the zip. Could you explain how I can reproduce the error?

Op do 11 apr 2024 om 10:11 schreef Amaninder Singh Gill <
***@***.***>:

**Comment by egonl** [comment] 2024-04-11 17:37
Thanks for the zip. Could you explain how I can reproduce the error with it?

**Comment by egonl** [comment] 2024-04-25 12:15
Can't reproduce, closing.

**Closed by egonl** 2024-04-25 12:15 UTC

**Comment by myriadtechluke** [comment] 2025-08-03 22:28
I'm also getting this issue. Current working theory is that the problem occurs when using a custom assembly load context to load SharpDocx.
